// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using Schadensapp.Database.Context;

#nullable disable

namespace Schadensapp.Migrations
{
    [DbContext(typeof(SchadensappDbContext))]
    [Migration("20230727085825_Mig1")]
    partial class Mig1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Schadensapp.Models.Database.Adresse", b =>
                {
                    b.Property<int>("AdresseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdresseID"));

                    b.Property<string>("Hausnummer")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("Postleitzahl")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Stadt")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Strasse")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("AdresseID");

                    b.ToTable("Adresses");
                });

            modelBuilder.Entity("Schadensapp.Models.Database.Bearbeitungsstelle", b =>
                {
                    b.Property<int>("BearbeitungsstelleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BearbeitungsstelleID"));

                    b.Property<string>("EMail")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("MapGruppe")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("BearbeitungsstelleID");

                    b.ToTable("Bearbeitungsstelles");
                });

            modelBuilder.Entity("Schadensapp.Models.Database.Dienstleister", b =>
                {
                    b.Property<int>("DienstleisterID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DienstleisterID"));

                    b.Property<string>("Abteilung")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("AdresseID")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("EMail")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Firmenname")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("NUMBER(1)");

                    b.HasKey("DienstleisterID");

                    b.ToTable("Dienstleisters");
                });

            modelBuilder.Entity("Schadensapp.Models.Database.Liegenschaft", b =>
                {
                    b.Property<int>("LiegenschaftID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LiegenschaftID"));

                    b.Property<int>("AdresseID")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("BearbeitungsstelleID")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("DienstleisterID")
                        .HasColumnType("NUMBER(10)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("Name")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("LiegenschaftID");

                    b.ToTable("Liegenschafts");
                });

            modelBuilder.Entity("Schadensapp.Models.Database.Meldung", b =>
                {
                    b.Property<string>("MeldungID")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("Anmerkung")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("BenutzerID")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Beschreibung")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<DateTime>("DatumUhr")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Dringlichkeit")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Ebene")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Gebäudeteil")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("LiegenschaftID")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Raum")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Status")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("MeldungID");

                    b.ToTable("Meldungs");
                });
#pragma warning restore 612, 618
        }
    }
}
